export const LOADING_VIEW = {
  SHOW: 'LOADING_VIEW_SHOW',
  HIDE: 'LOADING_VIEW_HIDE',
};

export const POPUP_ERROR = {
  SHOW: 'POPUP_ERROR_SHOW',
  HIDE: 'POPUP_ERROR_HIDE',
};

export const POPUP_SUCCESS = {
  SHOW: 'POPUP_SUCCESS_SHOW',
  HIDE: 'POPUP_SUCCESS_HIDE',
};

export const NAVIGATION_APP = {
  NAVIGATE: 'NAVIGATION_APP_NAVIGATE',
  BACK: 'NAVIGATION_APP_BACK',
  RESET: 'NAVIGATION_APP_RESET',
  REPLACE: 'NAVIGATION_APP_REPLACE',
  POP_CUSTOMS: 'NAVIGATION_APP_POP_CUSTOMS',
  ROUTE_NAME_SCREEN: 'ROUTE_NAME_SCREEN',
};
